export { default as Input } from './Input/Input'
export { default as Loader } from './Loader/Loader'
export { default as Button } from './Button/Button'
export { default as FileInput } from './FileInput/FileInput'
export { default as Eye } from './Eye/Eye'
export { default as InterlocutorMessage } from './InterlocutorMessage/InterlocutorMessage'
export { default as MyMessage } from './MyMessage/MyMessage'
export { default as Arrow } from './Arrow/Arrow'
export { default as Alert } from './Alert/Alert'
export { default as Typing } from './Typing/Typing'
export { default as Modal } from './Modal/Modal'
// export {default as } from ''
